# Generated by Django 4.2 on 2023-06-15 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("eui", models.CharField(blank=True, max_length=128, null=True)),
                ("last_consumption", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rssi", models.IntegerField(null=True)),
                ("snr", models.FloatField(null=True)),
                ("modinfo", models.CharField(blank=True, max_length=64, null=True)),
                ("codrate", models.CharField(blank=True, max_length=32, null=True)),
                ("freq", models.FloatField(null=True)),
                ("size", models.IntegerField(null=True)),
                ("volume", models.FloatField(null=True)),
                ("battery_level", models.FloatField(null=True)),
                ("payload", models.CharField(blank=True, max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smart_meter_api.device",
                    ),
                ),
            ],
        ),
    ]
